env:
  global:
    - PYTHONUNBUFFERED=yes
    - secure: "TyC3F7uBmd4iWLpUyhIDkpRfbhPUmRqFeFhr12VSHfzODQfeLBqB9hHMhhjVLlk1gsQwIXzNDY2X82U83d4gG0X+SEPDUpTimuWc/GJoJLQL4+uyfpS8seQWnxa7ZXkZrUdKb2owHtx+0ESzZwfOg+pd0OxoMenK9bcGo3hZtkk="

git:
  depth: 500

cache:
  directories:
    - $HOME/.cache/pip

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log


matrix:
  include:
    - env: PYTHON_VERSION=3.6 SUDO=true
      sudo: true
      language: generic
      os: linux
    - env: PYTHON_VERSION=3.5
      sudo: false
      language: generic
      os: linux
    - env: PYTHON_VERSION=2.7
      sudo: false
      language: generic
      os: linux
    - env: FLAKE8=true
      sudo: false
      language: python
      python: '3.5'
      os: linux
    - env: PYTHON_VERSION=3.6 SHELL_INTEGRATION=true
      sudo: false
      language: generic
      os: linux
      addons:
        apt:
          packages:
            - dash
            - zsh
    - env: PYTHON_VERSION=3.6 CONDA_BUILD=2.1.17
      sudo: false
      language: generic
      os: linux
    - env: PYTHON_VERSION=3.6 CONDA_BUILD=3.0.21
      sudo: false
      language: generic
      os: linux
    - env: PYTHON_VERSION=3.6
      sudo: false
      language: generic
      os: osx
  allow_failures:
    - os: osx
    - env: PYTHON_VERSION=3.6 CONDA_BUILD=3.0.21

install:
  - source utils/functions.sh && run_setup

script:
  - source utils/functions.sh && run_tests
